CREATE TABLE schoolcheck(
   id      INT  NOT NULL PRIMARY KEY 
  ,schoolname VARCHAR(255)
  ,adress  VARCHAR(255)
  ,zipcode VARCHAR(255)
  ,district VARCHAR(255)
  ,telnr   VARCHAR(255)
  ,email   VARCHAR(255)
  ,website VARCHAR(255)
  ,opendays VARCHAR(255)
  ,openclass VARCHAR(255)
  ,infonight VARCHAR(255)
  ,private VARCHAR(255)
  ,level   VARCHAR(255)
  ,concept VARCHAR(255)
  ,specials VARCHAR(255)
  ,tto     VARCHAR(255)
  ,sports  VARCHAR(255)
  ,tech    VARCHAR(255)
  ,spanish VARCHAR(255)
  ,vso     VARCHAR(255)
  ,vmboB   VARCHAR(255)
  ,vmboK   VARCHAR(255)
  ,vmboT   VARCHAR(255)
  ,havo    VARCHAR(255)
  ,vwo     VARCHAR(255)
  ,gymnasium VARCHAR(255)
  ,basis   VARCHAR(255)
  ,art     VARCHAR(255)
);
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (id,'schoolname','adress','zipcode','district','telnr','email','website','openday','openclass','infonight','private','level','concept','specials','tto','sports','tech','spanish','vso','vmbob','vmbok','vmbot','havo','vwo','gymnasium','basis','art');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (1,'Alex Grah Bellschool - Orion College West','Zekeringstraat 45','1014 BP','Amsterdam','020 611 1213','orioncollegewest@orion.nl','http://orioncollege.orion.nl/locatie-west-3-4','n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (2,'Altra College','Rode Kruisstraat 32','1025 KN','Amsterdam','020 555 8333',NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (3,'Altra College Amsterbaken','Transformatorweg 6','1014 AK','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (4,'Altra College Bascule FJP','Tafelbergweg 23','1105 BC','Zuidoost','020 563 2800',NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (5,'Altra College Noord','Purmerweg 116','1023 BB','Amsterdam','020 632 8090',NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (6,'Altra College School2care','Johan Braakensiekhof 31','1068 KK','Amsterdam','020 754 6150',NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (7,'Altra College West','Louis Couperusstraat 131','1064 CE','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (8,'Barlaeus Gymnasium','Weteringschans 31','1017 RV','Centrum','020 6263 396','mbosman@barlaeus.nl','http://www.barlaeus.nl','23-1-2016 10:00','27-01-16 14:00-16:00','n','n','Vwo Gymnasium','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','Y','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (9,'Berlage Lyceum','Pieter Lodewijk Takstraat 33','1073 KJ','Zuid','020 572 1200','info@berlagelyceum.eu','http://berlage.espritscholen.nl','28-01-2016 16:30-21:00 en 30-01-2016 10:00-13:00','10-02-16 14:30 - 16:30','10-02-16 19:30 - 21:00 (alleen ouders)','n','Vwo - Havo - Mavo - Vmbo - Vwo gymnasium','standaard','Esprit school','Y','N','Y','Y','N','N','N','Y','Y','Y','N','Algemeen Bijzonder','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (10,'Bindelmeer College','Dubbelink 1','1102 AL','Zuidoost','020 6990 221','bindelmeer@bindelmeercollege.nl','http://www.bindelmeercollege.nl','23-01-2016 11:00-17:00','n','n','n','Vmbo-k - Vmbo-b - Vmbo-t','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (11,'Bredero Beroepscollege (ROC)','Meeuwenlaan 132','1022 AM','Noord','020 5797 200','info@brederoberoepscollege.vova.nl','http://www.brederoberoepscollege.nl','23-01-2016 10:00-13:00 en 04-02-2016 18:30-20:30','n','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (12,'Bredero Lyceum (ROC)  (gaat door als Nieuwe Havo)','Buiksloterweg 85','1031 CG','Noord','020 5797 210','info@brederolyceum.vova.nl','http://www.brederolyceum.nl','nvt','n','n','n','Vwo - Havo','standaard','n.v.t.','N','N','N','N','N','N','N','N','Y','Y','N','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (13,'Bredero Mavo (ROC)','Gare du Nord 5','1022 LD','Noord','020 5797 230','info@brederomavo.vova.nl','http://www.brederomavo.nl','04-02-2016 18:30-20:30, 06-02-2016 10:00-13:00','n','n','n','Havo - Vmbo-t - Havo kansklas - Lwoo','standaard','Sportklas','Y','Y','N','N','N','N','N','Y','Y','N','N','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (14,'Caland 2','Anderlechtlaan 3','1066 HK','Nieuw West','020 6675 353','info@calandtwee.nl','http://www.calandtwee.nl','30-01-2016 10:00-13:00 en 02-02-2016 19:00-21:30','n','n','n','Vwo - Havo - Vmbo-t','standaard','n.v.t.','N','N','Y','N','N','N','N','Y','Y','Y','N','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (15,'Caland Lyceum','Pieter Calandlaan 182','1068 NT','Nieuw West','020 6675 353','info@calandlyceum.nl','https://www.calandlyceum.nl','25-01-2016 en 26-01-2016 en 18-02-2016 19:00-21:30','n','n','n','Vwo - Havo - Vmbo-t - Vwo gymnasium','standaard','Technasium','N','Y','N','N','N','N','N','Y','Y','Y','Y','Openbaar','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (16,'Calvijn met Junior College','calandlaan 3','1062 HE','Nieuw West','020 6153 409','calvijn@calvijnmjc.nl','http://www.calvijnmetjuniorcollege.nl','18-01-2015 16:00-19:00 en 09-03-2015 16:00-19:00','09-03-16 14:00-16:00','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','n.v.t.','N','N','Y','N','N','Y','Y','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (17,'Chr Sgm Buitenveldert','De Cuserstraat 3','1081 CK','Zuid','020 6423 902','administratie@csb-amsterdam.nl','http://www.csb-amsterdam.nl','04-02-2016 19:00-21:30 en 23-02-2016 19:00-21:30','n','n','n','Havo - Vmbo-t','standaard','Kopklas','N','N','N','N','N','N','N','Y','Y','N','N','Protestants-Christelijk','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (18,'Clusius College Amsterdam','Rode Kruisstraat 40','1025 KN','Noord','020 6363 636','amsterdam@clusius.nl','http://www.clusius.nl/vmbo/amsterdam/vmbo.aspx','29-01-2016 18:30-21:00 en 30-01-2016 10:00-13:00','n','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (19,'College De Meer','Radioweg 56','1098 NJ','Oost','020 6945 203','demeer@demeer.org','http://www.demeer.org','23-01-2016 10:00-13:00 en 03-02-2016 14:00-17:00 en 08-03-2016 18:30-21:00','08-030-16 18:30-21:00','n','n','Vmbo-t - Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (20,'Comenius Lyceum Amsterdam','Derkinderenstraat 44','1062 BJ','Nieuw West','020 6140 305','comenius@comeniuslyceum.nl','http://www.comeniuslyceum.nl','12-01-2016 en 04-02-2016 18:30','n','n','n','Vwo - Havo','standaard','Havo kansklas','N','N','N','N','N','N','N','N','Y','Y','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (21,'Cygnus Gymnasium','Vrolikstraat 8','1091 VG','Oost','020 4688 880','info@cygnusgymnasium.nl','http://www.cygnusgymnasium.nl','21-01-2016 19:30-21:30 en 03-02-2016 19:30-21:30','21-01-16 14:00-16:00 en 03-02-16 14:00-16:00','n','n','Vwo gymnasium','standaard','n.v.t.','N','N','Y','N','N','N','N','N','N','N','Y','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (22,'Damstede','Rode Kruisstraat 83','1025 KM','Noord','020 6352 360','damstede@damstede.net','http://damstede.mwp.nl','18-01-2016 19:00-21:30 en 19-01-2016 19:00-21:30','10-02-16 14:00-15:30 en 24-02-16 14:00-15:30','n','n','Vwo - Havo - Vwo gymnasium','standaard','Topsportregeling, dyslexie','N','Y','N','N','N','N','N','N','Y','Y','Y','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (23,'De Amsterdamsche School','Nieuwezijds Voorburgwal 68','1012 SE','Centrum','020 6254 690','info@amsterdamscheschool.nl','http://amsterdamscheschool.nl','op aanvraag','n','n','n','Vwo - Havo - Vmbo-t','standaard','n.v.t.','N','N','N','N','N','N','N','Y','Y','Y','N','Overig','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (24,'De Apollo','Oudaen 6','1081 BZ','Zuid','020 6448 357','Apollo@deapollo.nl','http://www.deapollo.nl','20-01-2016 16:00-18:30','n','16-02-16 19:30-21:00 (alleen ouders)','y','Vmbo-t + Lwoo - Havo + Lwoo - Havo kansklas','standaard','Tussenvoorziening','N','N','N','N','N','N','N','Y','Y','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (25,'Hubertus & Berkhoff','Betuwestraat 29','1079 PR','Zuid','020 5797 190','info@hubertusberkhoff.vova.nl','http://www.hubertusberkhoff.nl','21-01-2016 18:00-20:30 en 16-02-2016 18:00-20:30','06-04-16 14:00-15:00','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','TTO mogelijk','Y','N','N','N','N','Y','Y','Y','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (26,'De nieuwe Havo','Buiksloterweg 85','1031 CG','Noord','020 5797 177','info@denieuwehavo.vova.nl','http://www.denieuwehavo.nl','28-01-2016 19:00-21:00 en 30-01-2016 11:00-14:00','20-1 3-2 10-2 17-2 24-2-16 14:00-16:00','n','n','Havo','standaard','n.v.t.','N','N','N','N','N','N','N','N','Y','N','N','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (27,'De Nieuwe School','Herengracht 274','1016 BW','Centrum','020 623 4809','info@denieuweschool.com','http://www.denieuweschool.com','12-04-2016 20:00 en 21-06-2016 20:00','n','n','y','Vmbo - Havo - Vwo - vwo gymnasium','standaard','Cambridge English','N','N','N','N','N','N','N','Y','Y','Y','Y','Overig','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (28,'De Vinse School','Haarlemmerstraat 132 -136','1013 EX','Centrum','020 303 1020','info@vinseschool.nl','http://www.vinseschool.nl','11-01-2016 11:00-14:00','n','n','n','Vwo - Havo - Vmbo-t','standaard','n.v.t.','N','N','Y','N','N','N','N','Y','Y','Y','N','Overig/ AB?','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (29,'De Nieuwe Internationale School Esprit (DENISE)','Pieter de Hoochstraat 78','1071 EJ','Zuid','020 480 2700','info@denise.espritscholen.nl','http://denise.espritscholen.nl','24-2-2016','n','n','n','Vwo - Havo - Vmbo-t','standaard','International School','Y','N','Y','N','N','N','N','Y','Y','Y','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (30,'Amsterdam International Community School (AICS)','Prinses Irenestraat 59','1077 WW','Zuid','020 577 1240','info@aics.espritscholen.nl','http://aics.espritscholen.nl','23-01-2016 9:30-12:30','n','n','n','World School','standaard','Engelstalig','Y','N','N','N','N','N','N','N','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (31,'Marcanti College','Jan van Galenstraat 31','1051 KM','West','020 606 9000','info@marcanti.espritscholen.nl','http://marcanti.espritscholen.nl','04-02-2016 en 18-02-2016 16:00-20:00','n','n','n','Havo - Vmbo-t - Vmbo-k - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','N','Y','Y','Y','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (32,'Fons Vitae Lyceum','Reijnier Vinkeleskade 53','1071 SW','Zuid','020 571 2412','info@fonsvitae.nl','http://www.fonsvitae.nl','10-02-2016 15:00-18:00 en 20-02-2016 09:30-12:30','n','n','n','Vwo - Havo - Vwo gymnasium','standaard','n.v.t.','N','N','Y','N','N','N','N','N','Y','Y','Y','Katholiek','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (33,'Geert Groote College Amsterdam','Fred. Roeskestraat 84','1076 ED','Zuid','020 574 5830','info@ggca.nl','http://www.ggca.nl','30-01-2016 10:00-14:00 en 03-02-2016 16:00-19:00','n','n','n','Vwo - Havo - Vmbo-t','Vrije School','n.v.t.','N','N','N','N','N','N','N','Y','Y','Y','N','Algemeen Bijzonder','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (34,'Gerrit van der Veen College','Gerrit van der Veenstr 99','1077 DT','Zuid','020 679 9905','info@gerritvdveen.nl​','http://www.gerritvdveen.nl','18-01-2016 19:00-21:30 en 11-02-2016 19:00-21:30','18-02-16 13:45-15:45','n','n','Vwo - Havo','standaard','Dansklas','N','N','N','N','N','N','N','N','Y','Y','N','Interconfessioneel','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (35,'Havo De Hof (voorheen PNC2)','Linnaeushof 48','1098 KM','Oost','020 893 8000','info@havodehof.nl','http://www.havodehof.nl','28-01-16 en 9-02-16 19 21:00 en 30-01-16 12-15:00','20-01-16 en 17-02-16 13:30-15:00','n','n','Havo','standaard','n.v.t.','N','N','N','N','N','N','N','N','Y','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (36,'Hervormd Lyceum Zuid','Brahmsstraat 7','1077 HE','Zuid','020 662 7983','info@hlz.nl','http://www.hlz.nl','11-02-2016 16:00-20:30 en 23-02-2016 16:00-20:30','n','n','n','Vwo - Havo - Vwo gymnasium','standaard','n.v.t.','N','N','N','N','N','N','N','N','Y','Y','Y','Protestants Christelijk','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (37,'Het 4e Gymnasium (Esprit)','Stavangerweg 902','1013 AX','West','020 584 9010','info@het4egymnasium.nl','http://www.het4egymnasium.nl','04-02-2016 19:00-22:00 en 06-02-2016 10:00-23:00','10-02-16 13:45-16:00','n','n','Vwo Gymnasium','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','Y','Algemeen Bijzonder','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (38,'Het Amsterdams Lyceum','Valeriusplein 15','1075 BJ','Zuid','020 574 7744','handriessen@amsterdams.com','http://www.amsterdamslyceum.nl','20-02-2016 10:00-13:00','n','16 en 17-02-16 17:00-21:30 (ouders en kind)','n','Vwo - Vwo gymnasium','standaard','Spaans, Italiaans, Chinees','N','N','N','Y','N','N','N','N','N','Y','Y','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (39,'Cartesius Lyceum','Frederik Hendrikplantsoen 7A','1052 XN','West','020 584 9677','info@cartesius.espritscholen.nl','http://cartesius.espritscholen.nl','18-02-2016 18:00-21:00 en 20-02-16 10:00-13:00','n','n','n','Vwo - Havo','standaard','Spaanse les','N','N','N','Y','N','N','N','N','Y','Y','N','Interconfessioneel? AB?','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (40,'Het Hervormd Lyceum West','Hemsterhuisstraat 79','1065 XJ','Nieuw West','020 584 9677','school@hlw.nl','http://hlw.nl','02-02-2016 18:30-21:00 en 03-02-2016 18:30-21:00','17-02-16 14:30-16:30, 09-03-16 14:30-16:30','n','n','Vwo - Havo - Vmbo-t - Vwo gymnasium','standaard','Kopklas','Y','N','N','N','N','N','N','Y','Y','Y','Y','Protestants Christelijk','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (41,'Hogelant','Duinluststraat 20','1024 VK','Noord','020 634 4737','info@hogelant.nl','http://www.hogelant.nl','26-02-16 19.00-21.00','27-02-16 13:00-15:00','n','n','Vmbo - Vmbo-k - Vmbo-b - Lwoo','standaard','Tussenvoorziening','N','N','N','N','N','Y','Y','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (42,'Huygens College','2e C Huygensstr 31 +37','1054 NN','West','020 788 0880','p.schutt@huygens-college.nl','http://www.huygens-college.nl','10-02-16 15:00-17:30 en 19:00-21:00, 12-03-16 10:30-13:00','17-02-16 13:45-15:30','n','n','Vmbo-t - Vmbo-k - Vmbo-b, Vmbo - Lwoo','standaard','n.v.t.','N','Y','N','N','N','Y','Y','Y','N','N','N','Interconfessioneel','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (43,'Hyperion Lyceum (ROC)','Docklandsweg 2','1031 KN','Amsterdam','020 579 7220','info@hyperionlyceum.vova.nl','http://www.hyperionlyceum.nl','28-01-16 19:30-21:30 en 30-01-16 10:00-13:00','17-02-16 14:00-15:30','n','n','Vwo - Vwo gymnasium','standaard','Spaanse les','N','N','N','Y','N','N','N','N','N','Y','Y','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (44,'Iedersland College','Zekeringstraat 38-40','1014 BT','Amsterdam','020 408 1204',NULL,NULL,'n','n','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','Tussenvoorziening','N','N','N','N','N','Y','Y','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (45,'Ijburg College 1','Pampuslaan 1','1087 HP','Amsterdam','020 344 3000',NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (46,'Ijburg College 2','Foekje Dillemastraat 1','1095 MK','Amsterdam','020 344 3000',NULL,NULL,'n','n','n','n',NULL,'standaard','Kopklas','N','N','N','N','N','N','N','N','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (47,'IVKO - Leren van Kunst','Rustenburgerstraat 15','1074 EP','Amsterdam','020 597 9360',NULL,NULL,'n','n','n','n','Havo - Vmbo-t','standaard','n.v.t.','N','N','N','N','N','N','N','Y','Y','N','N','Algemeen Bijzonder','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (48,'Joodse SGM Maimonides','Noordbrabantstraat 15-17','1083 BE','Amsterdam','020 642 6161',NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Joods','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (49,'Keizer Karel College','Elegast 5','1185 AA','Amstelveen','020 641 5700',NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (50,'Kentalis Signus SOVSO','Jan Sluijtersstraat 9','1062 CJ','Amsterdam','020 617 8617',NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal Onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (51,'Kingmaschool','Beijerlandstraat 2','1025 NN','Amsterdam','020 - 519 50 70',NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal Onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (52,'Kolom Praktijkcollege de Atlant','Teilingen 4','1082 JS','Amsterdam','020 644 7290',NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Oecumenisch','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (53,'Kolom Praktijkcollege De Dreef','Alexander Dumaslaan 7','1102 WD','Amsterdam','020 519 5070',NULL,NULL,'n','n','n','n','Praktijkonderwijs','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Algemeen Bijzonder? Oe','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (54,'Kolom praktijkcollege Noord (KPCN)','Oostzanerdijk 139','1035 EX','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Praktijkonderwijs','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Oecumenisch','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (55,'Koninklijk Instituut voor Onderwijs van Slechtziende en Blinden','Slotermeerlaan 103','1063 JN','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal Onderwijs','N','N','Y','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (56,'LUCA Praktijkschool (ROC)','Javaplantsoen 24','1095 CS','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Praktijkonderwijs','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (57,'Luzac College','Passeerdersgracht 25','1016 XG','Amsterdam',NULL,NULL,NULL,'n','n','n','y','Vwo - Havo - Vmbo-t','standaard','Private','N','N','N','N','N','N','N','Y','Y','Y','N','Overig','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (58,'Luzac Lyceum','Uiterwaardenstraat 263','1079 CR','Amsterdam',NULL,NULL,NULL,'n','n','n','y','Vwo - Havo - Vmbo-t','standaard','Private','N','N','N','N','N','N','N','Y','Y','Y','N','Overig','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (59,'Mediacollega Amsterdam','Dintelstraat 15','1078 VN','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-k - Vmbo-b','standaard','n.v.t.','N','N','N','N','N','Y','Y','N','N','N','N','Algemeen Bijzonder','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (60,'Meridiaan College','Karel Klinkenbergstraat 1-3','1061 AH','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-t - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (61,'Metis Montessori Lyceum, mavo, havo (AVO)','Voormalige Stadstimmertuin 2','1018 ET','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Havo - Vmbo-t - Havo Special Class (voor autisten)','Montessori','Tussenvoorziening','N','N','N','N','N','N','N','Y','Y','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (62,'Metis Montessori Lyceum (MML)','Mauritskade 58','1092 AD','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vwo - Havo','Montessori','n.v.t.','N','N','N','N','N','N','N','N','Y','Y','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (63,'Montessori College Oost','Polderweg 3','1093 KL','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-t - Vmbo-k - Vmbo-b - Vmbo - Lwoo','Montessori','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (64,'Montessori Lyceum Amsterdam (MLA)','Pieter de Hoochstraat 59','1071 ED','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vwo - Havo - Vmbo-t - Vwo gymnasium','Montessori','n.v.t.','N','N','N','N','N','N','N','Y','Y','Y','Y','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (65,'Montessori Lyceum Amsterdam mavo-deelschool','Van Ostadestraat 103','1072 ST','Amsterdam',NULL,NULL,NULL,'n','n','n','n',NULL,'Montessori','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (66,'MUNDUS college Amsterdam (Esprit)','Burg. Hogguerstraat 2','1064 EB','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Parktijkonderwjs - Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','Tussenvoorziening?','N','N','N','N','N','Y','Y','N','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (67,'Open Schoolgemeenschap Bijlmer','Gulden Kruis 5','1103 BE','Amsterdam',NULL,NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (68,'Orion College Zuid','Gaasterlandstraat 7','1079 RH','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','N','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (69,'Over-Y College','Floraweg 170','1032 ZG','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-t','standaard','n.v.t.','N','Y','N','N','N','N','N','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (70,'Pieter Nieuwland College','Nobelweg 6','1097 AR','Amsterdam',NULL,NULL,NULL,'22-01-2016 en 12-02-2016 19-21:00','21-01-2016 en 11-02-2016 15:00-17:00','n','n','Vwo - Havo','standaard','VWO +, science/art, kopklas','N','N','N','N','N','N','N','N','Y','Y','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (71,'Praktijkcollege Het Plein (Kolom)','Jan de Louterpad 5','1063 ME','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Praktijkonderwijs','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N','Algemeen Bijzonder? Oe','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (72,'ROC op Maat West (16+)','Erik de Roodestraat 18','1056 AM','Amsterdam',NULL,NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (73,'ROC op Maat Zuidoost (16+)','Bijlmerdreef 1289','1103 TV','Amsterdam',NULL,NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (74,'Rosa BeroepsCollege Zorg en Welzijn','Schoenerstraat 7','1034 XZ','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (75,'Scholengemeenschap Panta Rhei','Pandora 1-2','1183 KK','Amstelveen',NULL,NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (76,'Scholengemeenschap Reigersbos / Exellius','Ravenswaaipad 3','1106 AW','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vwo - Havo - Vmbo-t - Vmbo-k','standaard','Exellius vwo, TTO, kopklas','Y','N','N','N','N','N','Y','Y','Y','Y','N','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (77,'Spinoza Lyceum Amsterdam','Peter van Anrooystraat 8','1076 BH','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vwo - Havo - Vmbo-t - Vwo gymnasium','Dalton','n.v.t.','N','N','N','N','N','N','N','Y','Y','Y','Y','Openbaar','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (78,'St Ignatiusgymnasium','Jan van Eijckstraat 47','1077 LH','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vwo gymnasium','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','Y','Katholiek','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (79,'St. Nicolaaslyceum','Beethovenplein 2','1077 WM','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vwo - Havo - Vwo gymnasium','standaard','n.v.t.','Y','Y','N','N','N','N','N','N','Y','Y','Y','Katholiek','Y');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (80,'Stelle College (ROC)','Mr. Treublaan 1 -3','1097 DP','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (81,'Stichting Joodse Kindergemeenschap Cheider Mavo Havo Vwo','Zeelandstraat 11','1082 BV','Amsterdam',NULL,NULL,NULL,'n','n','n','n',NULL,'standaard','n.v.t.','N','N','N','N','N','N','N','N','Y','Y','N','Joods','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (82,'Sweelinck College','Moreelsestraat 19 +21','1071 BJ','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-t - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','N','N','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (83,'Tobiasschool Nevenvestiging Zorg (ROC)','Poeldijkstraat 255','1059 VL','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','Vrije School','Tussenvoorziening','N','N','N','N','N','N','Y','Y','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (84,'Tyltylschool','Drostenburg 1','1102 AM','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (85,'Vossius Gymnasium','Messchaertstraat 1','1077 WS','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vwo gymnasium','standaard','n.v.t.','N','N','N','N','N','N','N','N','N','N','Y','Openbaar','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (86,'VSO Alphons Laudy (Kolom)','Van Nijenrodeweg 648','1082 AZ','Amsterdam',NULL,NULL,'www.kolom.net','n','n','n','n','Speciaal onderwijs','standaard','Speciaal onderwijs','N','N','N','N','N','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (87,'VSO De Heldring','Zuidelijke Wandelweg 30','1079 RK','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vso','standaard','Speciaal onderwijs','N','N','N','N','Y','N','N','N','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (88,'Waterlant College Ijdoorn','Rode Kruisstraat 14','1025 KN','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (89,'Wellantcollege Amsterdam Sloten','Jan van Zutphenstraat 60','1069 RS','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-k - Vmbo-b - Vmbo + Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (90,'Wellantcollege Linnaeus','Archimedesplantsoen 87','1098 JZ','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Praktijkonderwijs - Vmbo-k - Vmbo-b - Vmbo + Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Algemeen Bijzonder','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (91,'Winford Amsterdam VO','Speerstraat 6','1076 XN','Amsterdam',NULL,NULL,NULL,'n','n','n','y','Vwo - Havo - Vmbo','standaard','n.v.t.','N','N','N','N','N','N','N','Y','Y','Y','N',NULL,'N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (92,'Zuiderlicht College Vmbo Lwoo','Rustenburgerstraat 436 - 438','1072 HK','Amsterdam',NULL,NULL,NULL,'n','n','n','n','Vmbo-t - Vmbo-k - Vmbo-b - Vmbo - Lwoo','standaard','n.v.t.','N','N','N','N','N','Y','Y','Y','N','N','N','Interconfessioneel','N');
INSERT INTO schoolcheck(id,schoolname,adress,zipcode,district,telnr,email,website,opendays,openclass,infonight,private,level,concept,specials,tto,sports,tech,spanish,vso,vmboB,vmboK,vmboT,havo,vwo,gymnasium,basis,art) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
